// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7xDET1Ikurbm92b-uVRqJU2vpVotrdyI',
    appId: '1:798008126480:web:31cc7575bea1705ce2ee95',
    messagingSenderId: '798008126480',
    projectId: 'ulm-copro',
    authDomain: 'ulm-copro.firebaseapp.com',
    storageBucket: 'ulm-copro.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrpkQuBQwcr6CRi4yytHoW6NKS0vbEHXw',
    appId: '1:798008126480:android:7af10c065587d9a4e2ee95',
    messagingSenderId: '798008126480',
    projectId: 'ulm-copro',
    storageBucket: 'ulm-copro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbTgnxtVfpDYKvV3AVpVEpZRiBPjYfbrE',
    appId: '1:798008126480:ios:5363f0a6d551d8dae2ee95',
    messagingSenderId: '798008126480',
    projectId: 'ulm-copro',
    storageBucket: 'ulm-copro.firebasestorage.app',
    iosBundleId: 'com.example.ulmCopro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbTgnxtVfpDYKvV3AVpVEpZRiBPjYfbrE',
    appId: '1:798008126480:ios:5363f0a6d551d8dae2ee95',
    messagingSenderId: '798008126480',
    projectId: 'ulm-copro',
    storageBucket: 'ulm-copro.firebasestorage.app',
    iosBundleId: 'com.example.ulmCopro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7xDET1Ikurbm92b-uVRqJU2vpVotrdyI',
    appId: '1:798008126480:web:e3ecde1a24a67a47e2ee95',
    messagingSenderId: '798008126480',
    projectId: 'ulm-copro',
    authDomain: 'ulm-copro.firebaseapp.com',
    storageBucket: 'ulm-copro.firebasestorage.app',
  );
}
