// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdCvAj9DGGgiFAWpRAiXAY9KUqfrCRqBk',
    appId: '1:587625569088:web:47b00eed2063de24ac78a5',
    messagingSenderId: '587625569088',
    projectId: 'copro-aviation',
    authDomain: 'copro-aviation.firebaseapp.com',
    storageBucket: 'copro-aviation.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB81h2h_MA-SYo6ZQQWPmnVduBbNcOYHk0',
    appId: '1:587625569088:android:176d5c5d9ac8e143ac78a5',
    messagingSenderId: '587625569088',
    projectId: 'copro-aviation',
    storageBucket: 'copro-aviation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkchEw2KJDB4pctOGJUbByF4afiLTlJyI',
    appId: '1:587625569088:ios:eab9b7244ab83206ac78a5',
    messagingSenderId: '587625569088',
    projectId: 'copro-aviation',
    storageBucket: 'copro-aviation.firebasestorage.app',
    iosBundleId: 'com.example.coproAviation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkchEw2KJDB4pctOGJUbByF4afiLTlJyI',
    appId: '1:587625569088:ios:eab9b7244ab83206ac78a5',
    messagingSenderId: '587625569088',
    projectId: 'copro-aviation',
    storageBucket: 'copro-aviation.firebasestorage.app',
    iosBundleId: 'com.example.coproAviation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdCvAj9DGGgiFAWpRAiXAY9KUqfrCRqBk',
    appId: '1:587625569088:web:541fe6d97d588506ac78a5',
    messagingSenderId: '587625569088',
    projectId: 'copro-aviation',
    authDomain: 'copro-aviation.firebaseapp.com',
    storageBucket: 'copro-aviation.firebasestorage.app',
  );

}